version: '3.8' # specify the most recent version of Docker Compose

# specify which services (or containers) we want to have running within our Docker host.
# It’s possible to have multiple services running, but for now we just have one for web.
services:
  
  web:
    # We specify how to build the container by saying, Look in the current directory for the Dockerfile.
    build: .

    # Then within the container run the command to start up the local server.
    command: python /code/manage.py runserver 0.0.0.0:8000

    # mount automatically syncs the Docker filesystem with our local computer’s
    # filesystem. This means that we don’t have to rebuild the image each time we change a single file!
    volumes: 
      - .:/code

    # Lastly, we specify the ports to expose within Docker which will be 8000, which is the Django's default.
    ports:
      - 8000:8000

# docker-compose.yml file control how to run the container that will be built based upon our Dockerfile image.

# Docker container is a running instance
# of an image - the container is the actual, fully-built building


