# Generated by Django 3.1.4 on 2020-12-27 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20201227_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty_type',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Hard', 'Hard')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='flavor_type',
            field=models.CharField(choices=[('Sour', 'Sour'), ('Sweet', 'Sweet'), ('Salty', 'Salty')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method_type',
            field=models.CharField(choices=[('Cook', 'Cook'), ('Bake', 'Bake')], default=None, max_length=50),
        ),
    ]
