# Generated by Django 3.1.4 on 2021-01-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20201227_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty_type',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Hard', 'Hard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='flavor_type',
            field=models.CharField(blank=True, choices=[('Sour', 'Sour'), ('Sweet', 'Sweet'), ('Salty', 'Salty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method_type',
            field=models.CharField(blank=True, choices=[('Cook', 'Cook'), ('Bake', 'Bake')], max_length=50),
        ),
    ]
