# Generated by Django 3.1.4 on 2021-01-06 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210106_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.CharField(default={models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)}, max_length=200, unique=True),
        ),
    ]
