# Generated by Django 3.1.4 on 2021-01-06 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210106_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
