# Generated by Django 3.1.4 on 2021-01-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20210106_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='difficulty_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='method_type',
        ),
    ]
