# Generated by Django 3.1.4 on 2021-01-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20210106_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
