# Generated by Django 3.1.4 on 2021-01-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_auto_20210106_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='aupdated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
