# Generated by Django 3.1.4 on 2021-01-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_recipe_aupdated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='aupdated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
