# Generated by Django 3.1.4 on 2021-01-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_auto_20210106_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='aupdated_at',
            new_name='created_at',
        ),
    ]
