# Generated by Django 3.1.4 on 2020-12-27 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty_type',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Hard', 'Hard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='flavor_type',
            field=models.CharField(blank=True, choices=[('Sour', 'Sour'), ('Sweet', 'Sweet'), ('Salty', 'Salty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method_type',
            field=models.CharField(blank=True, choices=[('Cook', 'Cook'), ('Bake', 'Bake')], max_length=50),
        ),
    ]
