# Generated by Django 3.1.4 on 2020-12-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201227_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty_type',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Hard', 'Hard')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='flavor_type',
            field=models.CharField(blank=True, choices=[('Sour', 'Sour'), ('Sweet', 'Sweet'), ('Salty', 'Salty')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method_type',
            field=models.CharField(blank=True, choices=[('Cook', 'Cook'), ('Bake', 'Bake')], default=None, max_length=50),
        ),
    ]
