# Generated by Django 3.1.4 on 2021-01-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210105_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='method_type',
            field=models.CharField(choices=[('Cook', 'Cook'), ('Bake', 'Bake')], default=True, max_length=50),
        ),
    ]
